title: g1's blog
author: g1
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a new blog and it's still under building.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
